type Result<T> = std::result::Result<T, std::io::Error>;

fn main() -> Result<()> {
    // Your error-handling code here
    Ok(())
}
